name: Checkmarx AST Scan 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx AST Github Action
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@0fcee7e03446692b38464ac6ec3a47bf1deb1c27
      uses: Checkmarx/ast-github-action@2.0.9
      with:
    # Provide the AST portal URL
        base_uri: https://eu.ast.checkmarx.net
    # Provide the Tenant for AST portal URL
        cx_tenant: cx_cec_na_test_elco_garcia
    # Client ID for AST portal authentication
        cx_client_id: test_client
    # Secret key for AST portal authentication
        cx_client_secret: 2f75e9ec-14ae-403b-b1bf-27b3e73e4252
        additional_parameter: --sast-preset-name "Checkmarx Default"
